set nocompatible 
set fileformat=unix
set encoding=utf-8 
set number
syn on
set nocompatible
set backup
set backupdir=~/.vim/backup
set directory=~/.vim/tmp
set shiftwidth=4
set tabstop=4
set softtabstop=4
set ignorecase
set expandtab
set nopaste
set autoindent
set comments=sr:/*,mb:*,ex:*/
set noswapfile
set colorcolumn=80
set incsearch
set hlsearch
set wrapscan
set history=2000
set laststatus=2
set backspace=indent,eol,start
